### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-bifunctors#4]
@garyb I bumped the `const` dependency in `bower.json`. Does that need a major version bump?

**Comment by garyb** [comment]
Yeah, or at least that's what I've been doing now - a major version bump is propagated through all the dependant libraries. That list I made on `purescript-contravariant` is a toposorted list of transient dependencies.

**Comment by paf31** [comment]
Hmm, the build breaks after my commit, but I'm not sure why. It works for me locally.

**Comment by garyb** [comment]
Perhaps because the latest `psc` release doesn't have a `Semigroup Ordering` instance?

**Comment by paf31** [comment]
Oh right. Yeah, I'll try to make a release soon, after I merge a couple of PRs.
